interface IDate {
  START_DATE_HOURS_MINUTES: number;
  END_DATE_HOURS_MINUTES: number;
  START_DATE_DAY: number;
  END_DATE_DAY: number;
  START_DATE_MONTH: number,
  END_DATE_MONTH: number
}
export const DATE: IDate = {
  START_DATE_HOURS_MINUTES: 11,
  END_DATE_HOURS_MINUTES: 16,
  START_DATE_DAY: 8,
  END_DATE_DAY: 10,
  START_DATE_MONTH: 5,
  END_DATE_MONTH: 7,
};
